version: "3.8"
services:
  site:
    image: nginx:1.19.9
    volumes:
      - "./:/usr/share/nginx/html"
    ports:
      - 80
  builder:
    build: 
      context: .
      dockerfile: Dockerfile.builder
    volumes:
      - "./:/site"
    command: sass --watch styles.sass:styles.css --style compressed
